name: Release vNext channel

defaults:
  run:
    shell: bash

env:
  CI: true

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI | Next"]
    branches: [v5-dev]
    types:
      - completed

jobs:

  release-next:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: v5-dev
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup git
        run: |
          git config user.name "kendo-bot"
          git config user.email "kendouiteam@progress.com"

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install
        run: npm ci

      - name: Bootstrap
        run: npm run bootstrap

      - name: Build themes for dist
        run: |
          npm run sass:flat
          npm run dist:swatches

      - name: Lerna publish
        run: |
          printf "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npx lerna version --conventional-commits --conventional-prerelease --no-git-tag-version --no-push
          VERSION=$(node -e 'console.log(require("./lerna.json").version)')
          git add .
          git commit -m "chore(release): $VERSION"
          git tag $VERSION
          npx lerna publish from-package --preid dev --dist-tag dev --create-release github
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Push to GitHub
        run: |
          git push origin v5-dev --tags --quiet > /dev/null 2>&1
