name: Tag stable version

defaults:
  run:
    shell: bash

on: [workflow_dispatch]

jobs:

  tag:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Add token
        run: printf "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Tag stable version
        run: ./build/tag-stable.sh
